############################
## CHANGE THESE
############################

baseURL: "https://bnbhat.github.io/bnbhat.github.io.v4"
title: bnbhat.github.io.v4

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
