############################
## CHANGE THESE
############################

baseURL: "https://bnbhat.github.io"
title: Balachandra Bhat

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
