############################
## Author
############################

author:
  name: Balachandra Bhat
  image: author.png
  greeting: "Welcome to my portfolio website :tada:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/bnbhat
  - link: https://github.com/bnbhat/bnbhat.github.io#readme
  - website: https://bnbhat.com
  - x-twitter: https://x.com/balachandra311
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/balachandrabhat/
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: bhalu311@gmail.com
  #- discord: bnbhat
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  - medium: https://bnbhat.medium.com/
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: Balachandra Bhat
description: "my personal website"
images:
  - thumbnail.png
